version: '3'
services:
  app:
    image: node:20-alpine
    container_name: question-app
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: npm run start
  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: question-db
    volumes:
      - mysql-data-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_DATABASE: question
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql-data-volume: