version: '3'
services:
  app:
    container_name: nestjs-app
    build:
      context: ./docker/app/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: npm run start:dev
